### PR TITLE
removes unused dependency

### PR DESCRIPTION
**Pull request by dustinhayes**

### CODE REVIEW

**Comment by jonschlinkert** [comment]
wow, normally I lint before pushing up, don't know how I missed that! thanks!

**Comment by dustinhayes** [comment]
My pleasure! Thanks for writing a super useful module and giving it to the world.

**Comment by jonschlinkert** [comment]
:+1:

**Comment by jonschlinkert** [comment]
I'll be pushing up a version bump and publishing to npm this evening. thanks again!

**Comment by jonschlinkert** [comment]
done

**Pull request merged**
